### ISSUE TITLE
the library couldn't fetch posts from our web site

### ISSUE THREAD

**Issue by pishguy** [hooshyar/Flutter-Wordpress-Client#1]
could you help me why this library couldn't fetch posts from our website?

i installed two plugin as you introduced in read me, 

our website is:
http://www.farahessy.ir

**Comment by Disati** [comment]
Any updates on this?

**Comment by hooshyar** [comment]
I have tested your website and it works just fine.
please pull latest changes and read the readme file, if it didn't work send me the error log.
