### ISSUE TITLE
How to show only posts of certain categories?

### ISSUE THREAD

**Issue by Andymulb** [hooshyar/Flutter-Wordpress-Client#2]
Where do you provide the categoryIDs List as mentioned in client.dart?
`  /// Get all available posts.
  ///
  /// If [categoryIDs] list is provided then only posts within those categories
  /// will be returned. Use [injectObjects] to have full objects injected
  /// rather than just the object ID (i.e. a posts's featured media). The [page]
  /// and [perPage] parameters allow for pagination.`

**Comment by hooshyar** [comment]
Where ever you want to get posts from specific categories. do a Future builder and the future is : `client.listPosts(categoryIDs: [1,2,3,4])`
Example code:
```
                   FutureBuilder<List<Post>>(
                      future: client.listPosts(categoryIDs: [1,8]),
                      builder: (context, snapshot) {
                        if (snapshot.hasError) print(snapshot.error);

                        return snapshot.hasData
                            ? ListViewPosts(posts: snapshot.data)
                            : Center(child: CircularProgressIndicator());
                      },
```

**Comment by Andymulb** [comment]
Great, thank you very much!
I figured out that if there are e.g. two posts of a certain category, the featured images do not match with them but instead with the regular chronological order of all Wordpress posts. So if you display two posts of a certain category the first post's image is the featured image of the first of all posts, the second post's image is not its own featured image but the featured image of the second of all posts.
I will try to solve it.

**Comment by Andymulb** [comment]
I just replaced the `isExist()` function in the FutureBuilder of app.dart with `client.listPosts(categoryIDs: [1,2,3,4])`. It worked fine with hot reload but as soon as I restarted the app I received following error.
```
Exception caught by widgets library
The following NoSuchMethodError was thrown building ListViewPosts(dirty, state: ListViewPostsState#dfe9b):
The getter 'length' was called on null.
Receiver: null
Tried calling: length
```

**Comment by hooshyar** [comment]
please update your repository, I've made some changes.
