### ISSUE TITLE
No action on refresh

### ISSUE THREAD

**Issue by Andymulb** [hooshyar/Flutter-Wordpress-Client#3]
Refreshing is not working properly (in listView.dart). If you swipe down until the RefreshIndicator appears no new posts are shown. New posts only show up if you open and close one post no matter if you refreshed the page before. Is it possible to change the action on refresh so flutter rerenders the page with all posts?

```
RefreshIndicator(
            displacement: 150.0,
            onRefresh: isExitst,
            child: CustomScrollView(
              controller: scrollCont,
              slivers: <Widget>[
                SliverAppBarCustomized(),
                sliverListGlobal(widget.posts),      
                  
              ],
            ),
          ),
```

**Comment by hooshyar** [comment]
Fixed
