### ISSUE TITLE
Notification about new posts possible?

### ISSUE THREAD

**Issue by Andymulb** [hooshyar/Flutter-Wordpress-Client#4]
Is there a way to receive a notification in the notification bar as soon as a new post gets published?

**Comment by hooshyar** [comment]
it's possible, but I don't have time for that right now.

**Comment by the-farshad** [comment]
thats feature request, you have to use firebase messages for that.

**Comment by Andymulb** [comment]
> thats feature request, you have to use firebase messages for that.

But you cannot connect firebase to Wordpress, can you?

**Comment by the-farshad** [comment]
first save each post to firebase then notify the user using firebase messages

**Comment by the-farshad** [comment]
first, save each post to firebase then notify the user using firebase messages
