### ISSUE TITLE
hawalnir1 package missing

### ISSUE THREAD

**Issue by jmsperu** [hooshyar/Flutter-Wordpress-Client#5]
Hi, compilation exists with error about not finding package hawalnir1

**Comment by iqbalibrahim1992** [comment]
I reverted my version of flutter to 1.9.1hotfix2, then ran

`flutter clean`

Then 

`flutter doctor`

And finally ran the project again, and it was working for me. Originally was getting an issue about AndroidX although it wouldn't migrate to it. Done many hours of reading online to find the solution of reverting.
